### ISSUE TITLE
Pause overlay is visible after rotation

### ISSUE THREAD

**Issue by GRA0007** [torch2424/vaporBoy#100]
On a mobile device, after loading a rom, if the device is rotated, the "paused" overlay is visible on the screen despite the rom not actually being paused. Can only be removed by reloading.

**Comment by torch2424** [comment]
@GRA0007 Thanks for filing this issue! I'll test this out Asap and try to get a fix out!

Thanks for playing, and contributing back :)

**Comment by GRA0007** [comment]
@torch2424 thanks! Sorry my issue is kinda lacking emotion, used to giving bug reports when I do testing at work. I love this project and I hope it does really well!

**Comment by torch2424** [comment]
@GRA0007 You are welcome! And no worries at all, I'm just stoked someone cares enough to open an issue! And I'm soooooooo stoked you love the project! Definitely trying to get a lot more features out, and so far it's been doing pretty alright 😄 

Thanks again! Feel free to open any more bugs, or make any feature requests. I haven't updated the PROD app in a while, because I've been focused on accuracy in the [core WasmBoy](https://github.com/torch2424/wasmboy) project. But I'll definitely try to fix this bug soon (I want to say tonight or tommorrow) and get it pushed out, before updating with a TON of good new things 👍

**Comment by torch2424** [comment]
@GRA0007 So I fixed this issue in my branch `pause-rotate-fix`. But the best way for me was to just update to the latest WasmBoy, which had a fix in place for this :smile: 

However, I opened #102 which I'll need to fix as well in my next PR before I get this solved :cry:
