### ISSUE TITLE
Opening ROMs via the iOS Files app / file picker doesn't work

### ISSUE THREAD

**Issue by ahydronous** [torch2424/vaporBoy#139]
Trying to open a ROM via the file picker always leaves them greyed out, whether it's .zip or .gbc and regardless if it's stored locally or on iCloud or Dropbox.

I'm on iOS 14.3

**Comment by torch2424** [comment]
Hmmm that's odd! Thanks for the bug report! I'll look into this once I get the chance! :smile:

**Comment by lxgr** [comment]
The same thing happens on iOS 15 :(

**Comment by ahydronous** [comment]
@torch2424
Any chance of you quickly committing this fix? It would mean VaporBoy actually works with iOS, allowing us to play our old games without a jailbreak! ❤️

**Comment by torch2424** [comment]
My bad about the late review on this y'all! 😅 I shifted my main focus to my music career, rather than development, so I haven't been checking Github at all. But! I went ahead and tested the deploy preview, and this all works on my end. So merging! 😄 🎉 

Thank you VERY much @nuller1joe for the PR! I super super appreciate it! 🙏🏾 🎉 

cc @ahydronous & @lxgr
